#define MAX_GRAINS 140
#define MAX_PITCH 128
#define NUMBER_OF_SAMPLES 5
#define NUMBER_OF_SAMPLES_FLOAT 5.0
#define MAX_JITTER_SPREAD 3000.0
#define MAX_POSITION_FINE 2000.0
#define MAX_POSITION_MEDIUM 20000.0

// For the position display
#define DRAW_AREA_POSITION_X 5
#define DRAW_AREA_POSITION_Y 43
#define DRAW_AREA_WIDTH 270
#define DRAW_AREA_HEIGHT 20
