// Constants for patterns
#define DRAW_AREA_WIDTH 32.0
#define DRAW_AREA_HEIGHT 214.0
#define NUMBER_OF_SLIDERS 32
#define SLIDER_HEIGHT 214.0
#define SLIDER_WIDTH 32.0
#define SLIDER_HORIZONTAL_PADDING .8
#define DRAW_AREA_POSITION_X 9
#define DRAW_AREA_POSITION_Y 30 
