// Constants for patterns
#define DRAW_AREA_WIDTH 24.0
#define NUMBER_OF_SLIDERS 16
#define SLIDER_HEIGHT 310.0
#define SLIDER_WIDTH 24.0
#define SLIDER_HORIZONTAL_PADDING .8
#define DRAW_AREA_POSITION_X 9
#define DRAW_AREA_POSITION_Y 30
#define NUMBER_OF_BANKS 24
#define BANK_BUTTON_WIDTH 30.118
#define BANK_BUTTON_HEIGHT 30.118
#define BANK_BUTTONS_X 189.76
#define BANK_BUTTONS_Y 47.141
#define BANK_BUTTONS_PADDING 1.8
