#define DRAW_AREA_WIDTH 177
#define DRAW_AREA_HEIGHT 354.2
#define DRAW_AREA_POSITION_X 3.820
#define DRAW_AREA_POSITION_Y 4.250

#define TRIGGER_AT_BOTTOM 0
#define TRIGGER_AT_TOP 1
#define TRIGGER_AT_BOTH 2

#define CELL_WIDTH 21.5
#define CELL_HEIGHT 21.5
#define CELL_PADDING 0.64

#define SEQUENCER_ROWS 16
#define SEQUENCER_COLUMNS 8
