#define DRAW_AREA_WIDTH 177
#define DRAW_AREA_HEIGHT 354.2

#define TRIGGER_AT_BOTTOM 0
#define TRIGGER_AT_TOP 1
#define TRIGGER_AT_BOTH 2

#define CELL_WIDTH 19.0
#define CELL_HEIGHT 19.0
#define CELL_PADDING 2.25

#define SEQUENCER_ROWS 16
#define SEQUENCER_COLUMNS 8
