#define MAX_SEQUENCE_LENGTH 64
#define SEQUENCER_ROWS 16
#define SEQUENCER_COLUMNS 16
#define NUMBER_OF_TRIGGER_GROUPS 5

#define DRAW_AREA_WIDTH 277.4
#define DRAW_AREA_HEIGHT 277.4
#define DRAW_AREA_POSITION_X 3.800
#define DRAW_AREA_POSITION_Y 5.9

#define CELL_WIDTH 16.95
#define CELL_HEIGHT 16.95
#define CELL_PADDING 0.4

#define PLAY_MODE 0
#define EDIT_SEED_MODE 1
#define EDIT_TRIGGERS_MODE 2
#define EDIT_LENGTH_MODE 3
