#include "PNGPanel.hpp"
#include "Theme.hpp"
#include "VoxglitchModule.hpp"
#include "VoxglitchSamplerModule.hpp"
#include "VoxglitchSamplerModuleWidget.hpp"

#include "VoxglitchPorts.hpp"
#include "VoxglitchKnobs.hpp"
#include "VoxglitchPanel.hpp"
#include "VoxglitchSwitches.hpp"
#include "VoxglitchWidget.hpp"
#include "VoxglitchModuleWidget.hpp"
// #include "GrimeLayer.hpp"
