name: Build for Windows

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows x64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-jq
            unzip
            wget

      - name: Download and setup VCV Rack SDK
        run: |
          cd $HOME
          wget https://vcvrack.com/downloads/Rack-SDK-2.6.4-win-x64.zip
          unzip Rack-SDK-2.6.4-win-x64.zip

      - name: Cache FFmpeg build
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: |
            dep/lib
            dep/include
            dep/ffmpeg
          key: ffmpeg-6.1-windows-native-v1
          restore-keys: |
            ffmpeg-6.1-windows-native-

      - name: Build FFmpeg dependency
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          make dep RACK_DIR=$HOME/Rack-SDK

      - name: Build plugin
        run: |
          make -j$(nproc) RACK_DIR=$HOME/Rack-SDK

      - name: Create distribution package
        run: |
          make dist RACK_DIR=$HOME/Rack-SDK

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.vcvplugin
          name: win

      - name: Upload release assets (if tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.vcvplugin
          token: ${{ secrets.GITHUB_TOKEN }}
