name: Build VCV Rack Plugin for macOS

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

env:
  rack-sdk-version: 2.6.4

jobs:
  build-macos:
    name: macOS (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Note: FFmpeg is built as part of the build process, not a git submodule

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install build dependencies
      run: |
        brew update
        brew install wget git autoconf automake libtool pkg-config

    - name: Download and setup VCV Rack SDK
      run: |
        cd $HOME
        wget https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-mac-${{ matrix.arch }}.zip
        unzip Rack-SDK-${{ env.rack-sdk-version }}-mac-${{ matrix.arch }}.zip

        # Set environment variable for subsequent steps
        echo "RACK_DIR=$HOME/Rack-SDK" >> $GITHUB_ENV

    - name: Cache FFmpeg build
      id: cache-ffmpeg
      uses: actions/cache@v4
      with:
        path: |
          dep/lib
          dep/include
        key: ffmpeg-6.1-macos-${{ matrix.arch }}-v1
        restore-keys: |
          ffmpeg-6.1-macos-${{ matrix.arch }}-

    - name: Build FFmpeg dependency
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: |
        # Create dep directory
        mkdir -p dep

        # Set cross-compilation environment for arm64 on x64 runner
        export CROSS_COMPILE=${{ matrix.arch }}

        # Build FFmpeg using the Makefile target
        # This will clone, configure, and build FFmpeg with the correct settings
        make -j$(sysctl -n hw.ncpu) dep RACK_DIR=$HOME/Rack-SDK

    - name: Verify FFmpeg libraries
      run: |
        echo "Checking FFmpeg libraries:"
        ls -lh dep/lib/libav*.a || echo "FFmpeg libraries not found!"

        # Verify architecture of built libraries
        if [ -f dep/lib/libavcodec.a ]; then
          echo "Architecture of libavcodec.a:"
          lipo -info dep/lib/libavcodec.a
        fi

    - name: Build plugin
      run: |
        # Set cross-compilation for arm64 builds
        export CROSS_COMPILE=${{ matrix.arch }}

        # Build the plugin
        make -j$(sysctl -n hw.ncpu) RACK_DIR=$HOME/Rack-SDK

        # Verify the plugin was built and check its architecture
        ls -lh plugin.dylib
        echo "Plugin architecture:"
        lipo -archs plugin.dylib

    - name: Create distribution package
      run: |
        export CROSS_COMPILE=${{ matrix.arch }}

        # Create the distribution package
        make dist RACK_DIR=$HOME/Rack-SDK

        # List the created distribution files
        echo "Distribution files:"
        ls -lh dist/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: voxglitch-macos-${{ matrix.arch }}
        path: |
          dist/*.vcvplugin
        retention-days: 30

    - name: Upload release assets (if tagged)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.vcvplugin
        token: ${{ secrets.GITHUB_TOKEN }}
